(function(){
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={step:0,pieces:[],result:null};
const steps=['Panneau','Débit','Atelier','Plans 2D','Sorties','Validation QA'];
function uid(){return Math.random().toString(36).slice(2,9)}
function init(){renderSteps();loadCatalog();loadExample();bind();restore();updateHero();showStep(state.step);window.SpeedArtiModuleValidation?.init?.()}
function renderSteps(){const nav=$('#stepsNav');nav.innerHTML=steps.map((s,i)=>`<button class="step-btn" data-step="${i}"><span class="step-num">${i+1}</span>${s}</button>`).join('');nav.addEventListener('click',e=>{const b=e.target.closest('.step-btn');if(b)showStep(+b.dataset.step)})}
function loadCatalog(){const sel=$('#panelProduct');sel.innerHTML=window.SPEEDARTI_PANEL_CATALOG.map(p=>`<option value="${esc(p.id)}">${esc(p.supplier)} · ${esc(p.family)} · ${esc(p.label)}</option>`).join('');sel.addEventListener('change',applyPanel);applyPanel()}
function applyPanel(){const p=window.SPEEDARTI_PANEL_CATALOG.find(x=>x.id===$('#panelProduct').value)||window.SPEEDARTI_PANEL_CATALOG[0];$('#panelLength').value=p.length;$('#panelWidth').value=p.width;$('#panelThickness').value=p.thickness;$('#panelPrice').value=p.price;$('#panelGrain').checked=p.grain}
function loadExample(){state.pieces=[
 {id:uid(),rep:'A01',name:'Côté gauche',length:2200,width:550,qty:1,grain:'follow',rotation:'locked',edges:'A-AV'},
 {id:uid(),rep:'A02',name:'Côté droit',length:2200,width:550,qty:1,grain:'follow',rotation:'locked',edges:'A-AV'},
 {id:uid(),rep:'A03',name:'Tablette',length:900,width:550,qty:6,grain:'follow',rotation:'locked',edges:'AV'},
 {id:uid(),rep:'A04',name:'Dessus',length:900,width:600,qty:1,grain:'follow',rotation:'locked',edges:'AV'},
 {id:uid(),rep:'A05',name:'Socle',length:900,width:100,qty:2,grain:'free',rotation:'free',edges:'—'}
];renderPieces();state.result=null;renderResult();updateHero();window.SpeedArtiModuleValidation?.runAll?.()}
function addPiece(){const n=state.pieces.length+1;state.pieces.push({id:uid(),rep:`A${String(n).padStart(2,'0')}`,name:'Nouvelle pièce',length:800,width:400,qty:1,grain:'free',rotation:'free',edges:'—'});renderPieces();updateHero();window.SpeedArtiModuleValidation?.runAll?.()}
function renderPieces(){const b=$('#piecesBody');b.innerHTML=state.pieces.map((p,i)=>`<tr data-id="${esc(p.id)}"><td><input class="rep" data-k="rep" value="${esc(p.rep)}"></td><td><input class="desc" data-k="name" value="${esc(p.name)}"></td><td><input class="dim" type="number" min="1" data-k="length" value="${p.length}"></td><td><input class="dim" type="number" min="1" data-k="width" value="${p.width}"></td><td><input class="qty" type="number" min="1" data-k="qty" value="${p.qty}"></td><td><select class="grain" data-k="grain"><option value="free" ${p.grain==='free'?'selected':''}>Libre</option><option value="follow" ${p.grain==='follow'?'selected':''}>Suivre fil</option></select></td><td><select class="rotate" data-k="rotation"><option value="free" ${p.rotation==='free'?'selected':''}>Autorisée</option><option value="locked" ${p.rotation==='locked'?'selected':''}>Interdite</option></select></td><td><input class="edges" data-k="edges" value="${esc(p.edges||'—')}" title="Ex. AV, G/D/H/B"></td><td><button class="row-remove" data-remove="${esc(p.id)}" title="Supprimer">×</button></td></tr>`).join('');
 b.oninput=b.onchange=e=>{const tr=e.target.closest('tr');if(!tr)return;const p=state.pieces.find(x=>x.id===tr.dataset.id);const k=e.target.dataset.k;if(!p||!k)return;p[k]=['length','width','qty'].includes(k)?(e.target.value===''?NaN:Number(e.target.value)):e.target.value;state.result=null;renderResult();updateHero();autosave();window.SpeedArtiModuleValidation?.runAll?.()};
 b.onclick=e=>{const id=e.target.dataset.remove;if(id){state.pieces=state.pieces.filter(x=>x.id!==id);renderPieces();state.result=null;renderResult();updateHero();autosave();window.SpeedArtiModuleValidation?.runAll?.()}}
}
function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function cfg(){return {panelW:+$('#panelLength').value,panelH:+$('#panelWidth').value,panelThickness:+$('#panelThickness').value,panelPrice:+$('#panelPrice').value,panelGrain:$('#panelGrain').checked,kerf:+$('#kerf').value,trimLeft:+$('#trimLeft').value,trimRight:+$('#trimRight').value,trimTop:+$('#trimTop').value,trimBottom:+$('#trimBottom').value,scrapMinL:+$('#scrapMinL').value,scrapMinW:+$('#scrapMinW').value,scrapMinArea:+$('#scrapMinArea').value}}
function validate(){const gate=window.SpeedArtiModuleValidation?.gate?.('optimize');if(gate&&!gate.ok){const first=gate.report.checks.find(c=>['BLOCKING','WARNING'].includes(c.status)&&['Module','Projet','Catalogue','Panneau','Atelier','Débit','Exécution'].includes(c.domain));alert(first?`${first.id} — ${first.label}\n${first.detail}`:'Le rapport QA bloque le calcul.');showStep(5,true);return false}const c=cfg();if(c.panelW<=c.trimLeft+c.trimRight||c.panelH<=c.trimTop+c.trimBottom){alert('Les purges dépassent les dimensions exploitables du panneau.');return false}if(!state.pieces.length){alert('Ajoutez au moins une pièce.');return false}return true}
function optimize(){if(!validate())return;try{const strat=$('input[name="strategy"]:checked').value;state.result=window.SpeedArtiCutEngine.optimize(state.pieces,cfg(),strat);renderResult();autosave();const qa=window.SpeedArtiModuleValidation?.runAll?.();if(state.result?.impossible?.length||qa?.counts?.BLOCKING||qa?.counts?.WARNING)showStep(5,true);else showStep(3,true)}catch(error){state.result=null;renderResult();window.SpeedArtiModuleValidation?.captureRuntimeError?.(error?.message||error,'optimize');alert(`Erreur d’optimisation : ${error?.message||error}`);showStep(5,true)}}
function renderResult(){const r=state.result;if(!r){$('#emptyResult').classList.remove('hidden');$('#resultArea').classList.add('hidden');$('#technicalSummary').innerHTML='<div class="empty-inline">Lancez une optimisation pour générer le résumé technique.</div>';$('#scrapList').innerHTML='<div class="empty-inline">Aucune chute calculée.</div>';return}
 $('#emptyResult').classList.add('hidden');$('#resultArea').classList.remove('hidden');const c=cfg(),s=r.stats;
 const vals=[['Panneaux',r.sheets.length],['Pièces',r.sheets.reduce((a,x)=>a+x.items.length,0)],['Rendement',`${s.yieldPct.toFixed(1)} %`],['Chutes',r.scraps.length],['Coupes',s.cutCount],['Coût panneaux',`${(r.sheets.length*c.panelPrice).toFixed(2)} € HT`]];
 $('#statsGrid').innerHTML=vals.map(v=>`<div class="stat-card"><strong>${v[1]}</strong><span>${v[0]}</span></div>`).join('');
 $('#sheetsWrap').innerHTML=r.sheets.map(sh=>sheetHtml(sh,c)).join('');
 let seq=[];r.sheets.forEach(sh=>{seq.push(`<li><strong>Panneau ${sh.index}</strong> — purger les rives selon paramètres</li>`);sh.cuts.filter((_,i)=>i<Math.max(1,sh.items.length*2)).forEach((cut,i)=>seq.push(`<li>${esc(cut.label)}</li>`))});$('#cutSequence').innerHTML=seq.join('');
 renderSummary();renderScraps();updateHero();
}
function sheetHtml(sh,c){const W=c.panelW,H=c.panelH,max=920,scale=Math.min(max/W,520/H),vw=W*scale,vh=H*scale;const f=n=>n*scale;
 let svg=`<svg class="sheet-svg" width="${vw}" height="${vh}" viewBox="0 0 ${vw} ${vh}" xmlns="http://www.w3.org/2000/svg"><defs><pattern id="trim${sh.index}" width="8" height="8" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="8" height="8" fill="#fff5dc"/><line x1="0" y1="0" x2="0" y2="8" stroke="#deb96d" stroke-width="3"/></pattern></defs><rect x="0" y="0" width="${vw}" height="${vh}" fill="#fff" stroke="#526b82" stroke-width="2"/><rect x="0" y="0" width="${vw}" height="${f(c.trimTop)}" fill="url(#trim${sh.index})"/><rect x="0" y="${vh-f(c.trimBottom)}" width="${vw}" height="${f(c.trimBottom)}" fill="url(#trim${sh.index})"/><rect x="0" y="0" width="${f(c.trimLeft)}" height="${vh}" fill="url(#trim${sh.index})"/><rect x="${vw-f(c.trimRight)}" y="0" width="${f(c.trimRight)}" height="${vh}" fill="url(#trim${sh.index})"/>`;
 sh.free.forEach(fr=>{const scrap=fr.type==='scrap';svg+=`<rect x="${f(fr.x)}" y="${f(fr.y)}" width="${f(fr.w)}" height="${f(fr.h)}" fill="${scrap?'#dcfce7':'#f1f5f9'}" stroke="${scrap?'#75c795':'#b7c2cc'}" stroke-dasharray="4 3"/><text x="${f(fr.x)+5}" y="${f(fr.y)+14}" font-size="9" fill="${scrap?'#28704a':'#70808e'}">${scrap?'CHUTE':'déchet'} ${Math.round(fr.w)}×${Math.round(fr.h)}</text>`});
 sh.items.forEach((it,i)=>{const hue=210+(i%6)*8;svg+=`<rect x="${f(it.x)}" y="${f(it.y)}" width="${f(it.w)}" height="${f(it.h)}" fill="hsl(${hue} 80% 92%)" stroke="#4f8fdc" stroke-width="1.4"/><text x="${f(it.x)+5}" y="${f(it.y)+14}" font-size="10" font-weight="700" fill="#225589">${esc(it.rep)}</text><text x="${f(it.x)+5}" y="${f(it.y)+27}" font-size="8" fill="#3f6381">${Math.round(it.w)}×${Math.round(it.h)}${it.rotated?' ↻':''}</text>`});
 sh.cuts.forEach(cut=>{if(cut.axis==='V')svg+=`<line x1="${f(cut.x)}" y1="${f(cut.y)}" x2="${f(cut.x)}" y2="${f(cut.y+cut.length)}" stroke="#dc6060" stroke-width="${Math.max(1,f(cut.kerf))}" opacity=".45"/>`;else svg+=`<line x1="${f(cut.x)}" y1="${f(cut.y)}" x2="${f(cut.x+cut.length)}" y2="${f(cut.y)}" stroke="#dc6060" stroke-width="${Math.max(1,f(cut.kerf))}" opacity=".45"/>`});svg+='</svg>';
 const util=sh.items.reduce((a,i)=>a+i.w*i.h,0)/(c.panelW*c.panelH)*100;return `<article class="sheet-card"><div class="sheet-title"><strong>Panneau ${sh.index} · ${c.panelW} × ${c.panelH} × ${c.panelThickness} mm</strong><span>${sh.items.length} pièces · ${util.toFixed(1)} % occupé</span></div><div class="sheet-svg-wrap">${svg}</div></article>`}
function renderSummary(){const r=state.result;if(!r){$('#technicalSummary').innerHTML='<div class="empty-inline">Optimisation requise avant génération des sorties.</div>';return}const c=cfg(),p=window.SPEEDARTI_PANEL_CATALOG.find(x=>x.id===$('#panelProduct').value);const rows=[['Projet',$('#projectName').value],['Panneau',p?.label||'Panneau personnalisé'],['Format',`${c.panelW} × ${c.panelH} × ${c.panelThickness} mm`],['Panneaux nécessaires',r.sheets.length],['Pièces',r.sheets.reduce((a,s)=>a+s.items.length,0)],['Rendement',`${r.stats.yieldPct.toFixed(1)} %`],['Chutes récupérables',r.scraps.length],['Coupes indicatives',r.stats.cutCount],['Coût panneaux démo',`${(r.sheets.length*c.panelPrice).toFixed(2)} € HT`]];$('#technicalSummary').innerHTML=`<div class="summary-list">${rows.map(x=>`<div class="summary-row"><span>${esc(x[0])}</span><strong>${esc(x[1])}</strong></div>`).join('')}</div>`}
function renderScraps(){const r=state.result;if(!r){$('#scrapList').innerHTML='<div class="empty-inline">Optimisation requise avant calcul des chutes.</div>';return}const c=cfg();$('#scrapList').innerHTML=r.scraps.length?r.scraps.map(sc=>`<div class="scrap-card"><strong>${sc.id}</strong><span>Panneau ${sc.sheet} · ${Math.round(sc.w)} × ${Math.round(sc.h)} × ${c.panelThickness} mm</span><span>Surface ${(sc.w*sc.h/1e6).toFixed(3)} m² · à enregistrer au stock de chutes</span></div>`).join(''):'<div class="empty-inline">Aucune chute ne dépasse les seuils configurés.</div>'}
function updateHero(){const qty=state.pieces.reduce((a,p)=>a+(+p.qty||0),0);$('#heroPieces').textContent=qty;$('#heroSheets').textContent=state.result?state.result.sheets.length:'—';$('#heroYield').textContent=state.result?`${state.result.stats.yieldPct.toFixed(1)}%`:'—'}
function showStep(i,force=false){let target=Math.max(0,Math.min(steps.length-1,i));if(target===4&&!state.result&&!force){window.SpeedArtiModuleValidation?.runAll?.();target=5}state.step=target;$$('.page').forEach((p,n)=>p.classList.toggle('active',n===state.step));$$('.step-btn').forEach((b,n)=>{b.classList.toggle('active',n===state.step);b.classList.toggle('done',n<state.step)});$('#prevBtn').disabled=state.step===0;$('#nextBtn').textContent=state.step===steps.length-1?'Revenir aux plans':'Suivant →';if(state.step===4){renderSummary();renderScraps()}if(state.step===5)window.SpeedArtiModuleValidation?.runAll?.();window.scrollTo({top:0,behavior:'smooth'})}
function payloadBase(){const p=window.SPEEDARTI_PANEL_CATALOG.find(x=>x.id===$('#panelProduct').value),r=state.result,c=cfg();return {project:{name:$('#projectName').value,client:$('#projectClient').value,notes:$('#projectNotes').value},panel:{supplier:p?.supplier,product:p?.label,format:`${c.panelW}x${c.panelH}`,thickness:c.panelThickness,price:c.panelPrice},pieces:state.pieces,result:r?{sheets:r.sheets.length,yield:r.stats.yieldPct,scraps:r.scraps.length,cuts:r.stats.cutCount}:null}}
const maps={
 chiffrage:{title:'Envoyer au chiffrage — Menuisier / Agencement',note:'Le configurateur reste la source technique. Le chiffrage reçoit un brouillon de quantités et prestations, puis l’artisan complète prix, temps, pose et marge.',rows:[['Cible','Module Chiffrage → Menuisier / Agencement'],['Données','panneaux nécessaires, nombre de pièces, ml de chants, usinages, temps atelier estimé (futur)'],['Synchronisation','manuelle via « Mettre à jour le chiffrage » si le projet de découpe change']]},
 devis:{title:'Transformer en devis',note:'Création d’un brouillon de devis client à partir du projet technique. Le devis reste modifiable avant validation/envoi.',rows:[['Cible','service devis / quotes existant'],['Lignes proposées','fourniture panneaux, débit, chants, usinages, livraison éventuelle'],['Règle','aucune modification automatique d’un devis déjà validé : proposer une mise à jour manuelle']]},
 supplier_quote:{title:'Demander un devis fournisseur',note:'Réutilise le système SpeedArti existant de demandes de devis fournisseur. Aucun nouveau circuit achat n’est créé.',rows:[['Table entête','demandes_devis_fournisseurs'],['Lignes','demandes_devis_lignes'],['Réponse','reponses_devis_fournisseurs'],['Document','bucket privé devis-fournisseurs'],['À joindre','liste de débit + contraintes + plan 2D PDF + références panneau']]},
 supplier_order:{title:'Créer une commande fournisseur',note:'Réutilise la commande fournisseur existante. Si aucun devis fournisseur n’a été validé, la commande doit rester en brouillon avec alerte prix non validé.',rows:[['Table','commandes_fournisseurs'],['Contenu','fournisseur, chantier, lignes, montants, livraison, notes'],['Règle','reprendre le devis fournisseur validé quand disponible'],['Suivi','bénéficie du scan existant des commandes fournisseurs en retard']]}
};
function openIntegration(action){if(!state.result){optimize();if(!state.result)return}const gate=window.SpeedArtiModuleValidation?.gate?.('outputs');if(gate&&!gate.ok){alert('Le rapport QA contient une balise bloquante ou un avertissement. Corrigez-la avant de simuler un raccordement.');showStep(5,true);return}showStep(4,true);const m=maps[action];$('#modalTitle').textContent=m.title;$('#modalContent').innerHTML=`<p class="modal-note">${m.note}</p><div class="mapping">${m.rows.map(r=>`<div class="mapping-row"><strong>${r[0]}</strong><code>${r[1]}</code></div>`).join('')}<div class="mapping-row"><strong>Payload démo</strong><code>${esc(JSON.stringify(payloadBase(),null,2))}</code></div></div>`;$('#integrationModal').classList.remove('hidden');$('#modalConfirm').dataset.action=action}
function autosave(){const data={state:{pieces:state.pieces,step:state.step},form:{projectName:$('#projectName').value,projectClient:$('#projectClient').value,projectNotes:$('#projectNotes').value,panelProduct:$('#panelProduct').value,panelLength:$('#panelLength').value,panelWidth:$('#panelWidth').value,panelThickness:$('#panelThickness').value,panelPrice:$('#panelPrice').value,panelGrain:$('#panelGrain').checked,kerf:$('#kerf').value,trimLeft:$('#trimLeft').value,trimRight:$('#trimRight').value,trimTop:$('#trimTop').value,trimBottom:$('#trimBottom').value,scrapMinL:$('#scrapMinL').value,scrapMinW:$('#scrapMinW').value,scrapMinArea:$('#scrapMinArea').value}};try{localStorage.setItem('speedarti-cut-demo',JSON.stringify(data));$('#autosaveState').textContent='Enregistré localement';setTimeout(()=>$('#autosaveState').textContent='Projet local',1200)}catch(e){$('#autosaveState').textContent='Sauvegarde locale indisponible';window.SpeedArtiModuleValidation?.captureRuntimeWarning?.(e?.message||e,'localStorage')}}
function restore(){try{const d=JSON.parse(localStorage.getItem('speedarti-cut-demo'));if(!d)return;if(d.state?.pieces?.length){state.pieces=d.state.pieces;renderPieces()}Object.entries(d.form||{}).forEach(([k,v])=>{const e=$('#'+k);if(e){if(e.type==='checkbox')e.checked=!!v;else e.value=v}})}catch(e){console.warn(e)}}
function bind(){
 $('#addPieceBtn').onclick=addPiece;$('#loadExampleBtn').onclick=loadExample;$('#optimizeBtn').onclick=optimize;$('#optimizeTopBtn').onclick=optimize;$('#emptyOptimizeBtn').onclick=optimize;$('#saveBtn').onclick=autosave;$('#qaTopBtn').onclick=()=>showStep(5,true);if($('#printPlanBtn'))$('#printPlanBtn').onclick=()=>{if(!state.result){window.SpeedArtiModuleValidation?.runAll?.();alert('Aucun plan calculé à imprimer.');showStep(5,true);return}window.print()};$('#prevBtn').onclick=()=>showStep(state.step-1);$('#nextBtn').onclick=()=>showStep(state.step===steps.length-1?3:state.step+1);
 $$('.integration-btn').forEach(b=>b.onclick=()=>openIntegration(b.dataset.action));$('#modalClose').onclick=$('#modalCancel').onclick=()=>$('#integrationModal').classList.add('hidden');$('#modalConfirm').onclick=e=>{const a=e.currentTarget.dataset.action;$('#modalContent').insertAdjacentHTML('afterbegin',`<div class="success-flash">Simulation réussie : le connecteur « ${maps[a].title} » a reçu le projet. En production, cette étape appellera le service SpeedArti existant.</div>`)};
 $$('input,select,textarea').forEach(e=>{if(!e.closest('#piecesBody'))e.addEventListener('change',()=>{state.result=null;renderResult();updateHero();autosave();window.SpeedArtiModuleValidation?.runAll?.()})});
 $$('input[name="strategy"]').forEach(e=>e.addEventListener('change',()=>{$$('.strategy').forEach(x=>x.classList.remove('active'));e.closest('.strategy').classList.add('active')}));
}
window.SpeedArtiDemoAPI={getState:()=>state,getConfig:cfg,getIntegrations:()=>maps,showStep:(i)=>showStep(i,true),runOptimization:optimize,payloadBase};
init();
})();
